default: &default
  host: localhost
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: live_maps_development

test:
  <<: *default
  database: live_maps_test

production:
  <<: *default
  database: live_maps_production

staging:
  <<: *default
  database: live_maps_staging
