
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: live_maps_development
  username: postgres

test:
  <<: *default
  database: live_maps_test
  username: postgres

production:
  <<: *default
  database: live_maps_production
  username: live_maps
  password: <%= ENV['LIVE_MAPS_DATABASE_PASSWORD'] %>
